### ISSUE TITLE
Upgrade to find-parent-dir@v0.3.1 to resolve deprecation warning

### ISSUE THREAD

**Issue by kpruden** [thlorenz/resolve-bin#15] opened 2022-08-23 17:57 UTC
As of node 14.x the `main` field in `package.json` is deprecated. This field is specified in `find-parent-dir@v0.3.0` which results in a deprecation warning.

Upgrading to `v0.3.1` should resolve this. In the meantime I can work around this by using an explicit resolution override.

(see https://github.com/thlorenz/find-parent-dir/issues/8)

**Comment by bendrucker** [comment] 2022-08-23 18:30
Duplicate of #9

**Closed as completed by bendrucker** 2022-08-23 18:30 UTC
